import photo from "../assets/mobile-picture.jpg";

const datas = [
  {
    id: 1,
    picture: photo,
    brand: "APPLE",
    name: "IPHONE 8",
    model: "test",
    ram: "16",
    storage: 60,
    screen: "4",
    network: false,
    price: "250,00 €",
    reconditionned: true,
    newMobile: false,
    good: true,
  },
  {
    id: 2,
    picture: photo,
    brand: "SAMSUNG",
    name: "SAMSUNG GALAXY",
    model: "test",
    ram: "8",
    storage: 100,
    screen: "6",
    network: true,
    price: "100,00 €",
    reconditionned: true,
    newMobile: false,
    good: true,
  },
  {
    id: 3,
    picture: photo,
    brand: "SAMSUNG",
    name: "SAMSUNG S",
    model: "test",
    ram: "8",
    storage: 50,
    screen: "5",
    network: true,
    price: "80,00 €",
    reconditionned: false,
    newMobile: true,
    good: true,
  },
  {
    id: 4,
    picture: photo,
    brand: "LG",
    name: "LG 10",
    model: "test",
    ram: "4",
    storage: 30,
    screen: "5",
    network: false,
    price: "50,00 €",
    reconditionned: true,
    newMobile: false,
    good: false,
  },
];

export default datas;
